/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function lexicalScore(text: string, query: string): number
export declare function validateConfig(configJson: string): string
